name: Merge mainline to main # all passing tests on mainline will be merged to main

on:
  workflow_run:
    workflows: ["Run Tests"] # Trigger this workflow after the "Run Tests" workflow completes
    types:
      - completed # Trigger on completion of the "Run Tests" workflow

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/mainline' }} # Run this job only if the "Run Tests" workflow was successful and the branch is "mainline"
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Check out the repository code

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'  # Configure Git user name
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'  # Configure Git user email

      - name: Merge mainline into main
        run: |
          git checkout main  # Check out the main branch
          git pull origin main  # Pull the latest changes from the main branch
          git merge mainline  # Merge the mainline branch into the main branch
          git push origin main  # Push the merged changes to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authentication
